### ISSUE TITLE
Puis-je utiliser dictionaries/easy_french.txt pour mon propre projet libre (mais sous licence MIT et pas GPL)

### ISSUE THREAD

**Issue by Naereen** [nicolasfostier/DrawingLeague#1]
Bonjour @nicolasfostier.
Merci de ce beau projet.
Puis-je utiliser dictionaries/easy_french.txt pour mon propre projet libre, mais qui est sous licence MIT et pas GPL ?
https://github.com/Naereen/Free-dictionnaries-for-Pictionnary
Merci d'avance !
@Naereen

**Comment by nicolasfostier** [comment]
Bonjour @Naereen. 
Il n'y a pas de soucis, je vous autorise à utiliser ma liste de mots pour votre projet.

**Comment by Naereen** [comment]
Merci @nicolasfostier !
